### ISSUE TITLE
Style: Use double quotes for attributes

### ISSUE THREAD

**Issue by castavridis** [jwebs3/Cat_Costume_Project#1]
For style points, use double quotes, `"`, for attributes!

Although there's no difference to some [sources](https://stackoverflow.com/questions/2373074/single-vs-double-quotes-vs), most developers use double quotes for HTML attributes. Also, when you inspect pages, you may notice that web inspector uses double quotes for attributes as well.

(Since this is a smaller project, you may be able to get a way with finding `'` and replacing all with `"`.)

https://github.com/jwebs3/Cat_Costume_Project/blob/f60dde56853c33c3c6a217e7c161c83beeff2989/index.html#L9

**Comment by jwebs3** [comment]
fixed
