### ISSUE TITLE
Typo: Minor typo with the multi-line comment

### ISSUE THREAD

**Issue by castavridis** [jwebs3/Cat_Costume_Project#3]
Multi-line comments in CSS look like this: `/* Hello! */`.

You may also notice your code-editor changes color for the entire comment.

https://github.com/jwebs3/Cat_Costume_Project/blob/f60dde56853c33c3c6a217e7c161c83beeff2989/assets/css/index.css#L5

**Comment by jwebs3** [comment]
fixed
