### ISSUE TITLE
Q: `!important` let's talk about why you're using it

### ISSUE THREAD

**Issue by castavridis** [jwebs3/Cat_Costume_Project#5]
Sometimes `!important` is a symptom of CSS that could be organized differently.

https://github.com/jwebs3/Cat_Costume_Project/blob/f60dde56853c33c3c6a217e7c161c83beeff2989/assets/css/index.css#L12

**Comment by jwebs3** [comment]
fixed - was left over from when I was trying to get something to work. removing it did not change anything
