### ISSUE TITLE
Fix: Font-family font stack

### ISSUE THREAD

**Issue by castavridis** [jwebs3/Cat_Costume_Project#6]
Font-family is a font stack, bold doesn't quite work the way you would expect here; even though it's not doing any harm to the display of your web page. Font-stacks are basically a list of different fonts you want to use incase the first font, in this case 'PT Sans Narrow' doesn't load.

More info here: https://css-tricks.com/snippets/css/font-stacks/

https://github.com/jwebs3/Cat_Costume_Project/blob/f60dde56853c33c3c6a217e7c161c83beeff2989/assets/css/index.css#L8

**Comment by jwebs3** [comment]
fixed
